# Generated by Django 2.1.7 on 2019-04-04 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Start'), ('P', 'Process'), ('D', 'Done'), ('E', 'Error'), ('A', 'Abort')], max_length=1)),
                ('bar_type', models.CharField(choices=[('T', 'Tick'), ('M', 'Minute'), ('D', 'Day')], max_length=1)),
                ('total_profit_percent', models.FloatField(max_length=15)),
                ('year_profit_percent', models.FloatField(max_length=15)),
                ('max_dropdown_percent', models.FloatField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('S', 'Stock'), ('F', 'Futures'), ('C', 'CryptoCurrency'), ('O', 'Other')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StrategyCode'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Strategy'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StrategyCode'),
        ),
    ]
