# Generated by Django 2.2.1 on 2019-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='max_dropdown_percent',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='total_profit_percent',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='year_profit_percent',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
