# Generated by Django 2.1.7 on 2019-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
