# Generated by Django 2.1.7 on 2019-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190404_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategycode',
            name='code_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
